apiVersion: "kubernetes-client.io/v1"
kind: ExternalSecret
metadata:
  name: alex-credentials
  namespace: teste-secrets
spec:
  refreshInterval: 15s
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target: alex-credentials-01
  data:
  - secretKey: username
    remoteRef:
      key: secret/vault/teste
      property: username
